services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - DB_PORT=3306
        # Use 'db' as the hostname
      - MYSQL_DATABASE=imdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    networks:
      - nodejs-mysql-network



  db:
    image: mysql:latest
    ports:
      - "3307:3306"  # Map host port 3307 to container port 3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=imdb
    networks:
      - nodejs-mysql-network
    volumes:
      - mysql_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

networks:
  nodejs-mysql-network:
    name: nodejs-mysql-network

volumes:
  mysql_data: